comp: main.c rok_narodzin.c rok_obecny.c
	gcc -c main.c rok_narodzin.c rok_obecny.c
main: main.o rok_narodzin.o rok_obecny.o
	cc main.o rok_narodzin.o rok_obecny.o

clean: rm -f *.o *~ main
	rm -f *.o *~ main
